name: .conda
dependencies:
  - jupyter
  - matplotlib
  - geopandas
  - ipympl
  - pip
  - pip:
    - ipyfilechooser
    - opencv-python
    - git+https://github.com/emotional-cities/pluma-analysis.git@500fee94ec99103c1a72cd9bfb2556b639b4319b