name: .conda
dependencies:
  - jupyter
  - matplotlib
  - geopandas
  - ipympl
  - pip
  - pip:
    - ipyfilechooser
    - opencv-python
    - git+https://github.com/emotional-cities/pluma-analysis.git